// AUTO-GENERATED by appkit — 직접 수정 금지. 정본: C:/dev/tools/appkit (python sync.py)
//
// 공통 조상 토큰 v1.1.0 — 앱: facing
// 마스터: tools/appkit/master/appkit.json / 스킨: appkit.config.json
import 'package:flutter/material.dart';

/// 앱 셸 공통 조상 토큰. 앱 코드는 이 값을 직접 쓰거나
/// 앱 테마(FacingTokens 등)가 이 값을 재수출한다.
class AppKit {
  AppKit._();

  static const String version = '1.1.0';
  static const String brandName = 'HYPHEN';
  static const String fontFamily = 'Pretendard';

  // ==== 뉴트럴·상태 컬러 (공통 조상) ====
  static const Color bg = Color(0xFFFAFAFA);
  static const Color surface = Color(0xFFFFFFFF);
  static const Color surfaceAlt = Color(0xFFF5F5F5);
  static const Color surfaceHover = Color(0xFFF0F0F0);
  static const Color text = Color(0xFF18181B);
  static const Color textSub = Color(0xFF52525B);
  static const Color muted = Color(0xFF71717A);
  static const Color placeholder = Color(0xFFA1A1AA);
  static const Color border = Color(0xFFE4E4E7);
  static const Color borderStrong = Color(0xFFD4D4D8);
  static const Color success = Color(0xFF047857);
  static const Color successBg = Color(0xFFECFDF5);
  static const Color warning = Color(0xFFB45309);
  static const Color warningBg = Color(0xFFFEF3C7);
  static const Color danger = Color(0xFFB91C1C);
  static const Color dangerBg = Color(0xFFFEF2F2);
  static const Color info = Color(0xFF2563EB);
  static const Color infoBg = Color(0xFFEEF2FF);
  static const Color onAccent = Color(0xFFFFFFFF);

  // ==== 브랜드 스킨 (앱별 config) ====
  static const Color accent = Color(0xFFCC1F1F);
  static const Color accentPressed = Color(0xFFB91C1C);
  static const Color accentSoft = Color(0xFFFEF2F2);

  // ==== 타이포 스케일 9단 ====
  static const double displaySize = 56;
  static const FontWeight displayWeight = FontWeight.w900;
  static const double displayLs = -1.68;
  static const double displayLh = 1.0;
  static const double h1Size = 28;
  static const FontWeight h1Weight = FontWeight.w700;
  static const double h1Ls = -0.56;
  static const double h1Lh = 1.2;
  static const double h2Size = 22;
  static const FontWeight h2Weight = FontWeight.w700;
  static const double h2Ls = -0.33;
  static const double h2Lh = 1.25;
  static const double h3Size = 17;
  static const FontWeight h3Weight = FontWeight.w600;
  static const double h3Ls = -0.17;
  static const double h3Lh = 1.3;
  static const double leadSize = 18;
  static const FontWeight leadWeight = FontWeight.w400;
  static const double leadLs = -0.18;
  static const double leadLh = 1.45;
  static const double bodySize = 15;
  static const FontWeight bodyWeight = FontWeight.w400;
  static const double bodyLs = -0.15;
  static const double bodyLh = 1.5;
  static const double captionSize = 13;
  static const FontWeight captionWeight = FontWeight.w400;
  static const double captionLs = -0.13;
  static const double captionLh = 1.45;
  static const double microSize = 13;
  static const FontWeight microWeight = FontWeight.w500;
  static const double microLs = -0.13;
  static const double microLh = 1.4;
  static const double labelSize = 12;
  static const FontWeight labelWeight = FontWeight.w600;
  static const double labelLs = 1.32;
  static const double labelLh = 1.2;

  // ==== 스페이싱 ====
  static const double sp1 = 4;
  static const double sp2 = 8;
  static const double sp3 = 12;
  static const double sp4 = 16;
  static const double sp5 = 24;
  static const double sp6 = 32;
  static const double sp7 = 48;
  static const double sp8 = 64;

  // ==== 모서리 ====
  static const double r1 = 4;
  static const double r2 = 8;
  static const double r3 = 12;
  static const double r4 = 16;
  static const double r5 = 28;

  // ==== 크기 ====
  static const double touchMin = 48;
  static const double buttonH = 52;
  static const double appBarH = 52;
  static const double tabbarH = 64;

  // ==== 모션 ====
  static const Duration motionPress = Duration(milliseconds: 100);
  static const Duration motionBase = Duration(milliseconds: 150);
  static const Duration motionPage = Duration(milliseconds: 250);
  static const Duration splashMin = Duration(milliseconds: 2500);
  static const Duration splashFade = Duration(milliseconds: 300);

  // ==== 공통 UI 문자열 (스킨: 앱별 언어·톤) ====
  static const String strSkip = '건너뛰기';
  static const String strNext = '다음';
  static const String strStart = '시작';
  static const String strSave = '저장';
  static const String strCancel = '취소';
  static const String strLoading = '불러오는 중';
  static const String strOffline = '오프라인 · 연결 시 동기화';
  static const String strRetry = '다시 시도';
  static const String strDone = '완료';
  static const String strEdit = '수정';
}
